version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: bd2-postgres
    environment:
      POSTGRES_USER: bd2_user
      POSTGRES_PASSWORD: bd2_password
      POSTGRES_DB: bd2_database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: bd2-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  postgres_data:
