// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	models "github.com/susek555/BD2/car-dealer-api/internal/models"
	views "github.com/susek555/BD2/car-dealer-api/internal/views"
)

// AuctionRepositoryInterface is an autogenerated mock type for the AuctionRepositoryInterface type
type AuctionRepositoryInterface struct {
	mock.Mock
}

type AuctionRepositoryInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *AuctionRepositoryInterface) EXPECT() *AuctionRepositoryInterface_Expecter {
	return &AuctionRepositoryInterface_Expecter{mock: &_m.Mock}
}

// BuyNow provides a mock function with given fields: _a0, userID
func (_m *AuctionRepositoryInterface) BuyNow(_a0 *models.Auction, userID uint) error {
	ret := _m.Called(_a0, userID)

	if len(ret) == 0 {
		panic("no return value specified for BuyNow")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Auction, uint) error); ok {
		r0 = rf(_a0, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AuctionRepositoryInterface_BuyNow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BuyNow'
type AuctionRepositoryInterface_BuyNow_Call struct {
	*mock.Call
}

// BuyNow is a helper method to define mock.On call
//   - _a0 *models.Auction
//   - userID uint
func (_e *AuctionRepositoryInterface_Expecter) BuyNow(_a0 interface{}, userID interface{}) *AuctionRepositoryInterface_BuyNow_Call {
	return &AuctionRepositoryInterface_BuyNow_Call{Call: _e.mock.On("BuyNow", _a0, userID)}
}

func (_c *AuctionRepositoryInterface_BuyNow_Call) Run(run func(_a0 *models.Auction, userID uint)) *AuctionRepositoryInterface_BuyNow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.Auction), args[1].(uint))
	})
	return _c
}

func (_c *AuctionRepositoryInterface_BuyNow_Call) Return(_a0 error) *AuctionRepositoryInterface_BuyNow_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AuctionRepositoryInterface_BuyNow_Call) RunAndReturn(run func(*models.Auction, uint) error) *AuctionRepositoryInterface_BuyNow_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: _a0
func (_m *AuctionRepositoryInterface) Create(_a0 *models.Auction) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Auction) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AuctionRepositoryInterface_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type AuctionRepositoryInterface_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - _a0 *models.Auction
func (_e *AuctionRepositoryInterface_Expecter) Create(_a0 interface{}) *AuctionRepositoryInterface_Create_Call {
	return &AuctionRepositoryInterface_Create_Call{Call: _e.mock.On("Create", _a0)}
}

func (_c *AuctionRepositoryInterface_Create_Call) Run(run func(_a0 *models.Auction)) *AuctionRepositoryInterface_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.Auction))
	})
	return _c
}

func (_c *AuctionRepositoryInterface_Create_Call) Return(_a0 error) *AuctionRepositoryInterface_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AuctionRepositoryInterface_Create_Call) RunAndReturn(run func(*models.Auction) error) *AuctionRepositoryInterface_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllActiveAuctions provides a mock function with no fields
func (_m *AuctionRepositoryInterface) GetAllActiveAuctions() ([]views.SaleOfferView, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllActiveAuctions")
	}

	var r0 []views.SaleOfferView
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]views.SaleOfferView, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []views.SaleOfferView); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]views.SaleOfferView)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AuctionRepositoryInterface_GetAllActiveAuctions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllActiveAuctions'
type AuctionRepositoryInterface_GetAllActiveAuctions_Call struct {
	*mock.Call
}

// GetAllActiveAuctions is a helper method to define mock.On call
func (_e *AuctionRepositoryInterface_Expecter) GetAllActiveAuctions() *AuctionRepositoryInterface_GetAllActiveAuctions_Call {
	return &AuctionRepositoryInterface_GetAllActiveAuctions_Call{Call: _e.mock.On("GetAllActiveAuctions")}
}

func (_c *AuctionRepositoryInterface_GetAllActiveAuctions_Call) Run(run func()) *AuctionRepositoryInterface_GetAllActiveAuctions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *AuctionRepositoryInterface_GetAllActiveAuctions_Call) Return(_a0 []views.SaleOfferView, _a1 error) *AuctionRepositoryInterface_GetAllActiveAuctions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AuctionRepositoryInterface_GetAllActiveAuctions_Call) RunAndReturn(run func() ([]views.SaleOfferView, error)) *AuctionRepositoryInterface_GetAllActiveAuctions_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: id
func (_m *AuctionRepositoryInterface) GetByID(id uint) (*models.Auction, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.Auction
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (*models.Auction, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uint) *models.Auction); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Auction)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AuctionRepositoryInterface_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type AuctionRepositoryInterface_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - id uint
func (_e *AuctionRepositoryInterface_Expecter) GetByID(id interface{}) *AuctionRepositoryInterface_GetByID_Call {
	return &AuctionRepositoryInterface_GetByID_Call{Call: _e.mock.On("GetByID", id)}
}

func (_c *AuctionRepositoryInterface_GetByID_Call) Run(run func(id uint)) *AuctionRepositoryInterface_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint))
	})
	return _c
}

func (_c *AuctionRepositoryInterface_GetByID_Call) Return(_a0 *models.Auction, _a1 error) *AuctionRepositoryInterface_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AuctionRepositoryInterface_GetByID_Call) RunAndReturn(run func(uint) (*models.Auction, error)) *AuctionRepositoryInterface_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: _a0
func (_m *AuctionRepositoryInterface) Update(_a0 *models.Auction) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Auction) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AuctionRepositoryInterface_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type AuctionRepositoryInterface_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - _a0 *models.Auction
func (_e *AuctionRepositoryInterface_Expecter) Update(_a0 interface{}) *AuctionRepositoryInterface_Update_Call {
	return &AuctionRepositoryInterface_Update_Call{Call: _e.mock.On("Update", _a0)}
}

func (_c *AuctionRepositoryInterface_Update_Call) Run(run func(_a0 *models.Auction)) *AuctionRepositoryInterface_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.Auction))
	})
	return _c
}

func (_c *AuctionRepositoryInterface_Update_Call) Return(_a0 error) *AuctionRepositoryInterface_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AuctionRepositoryInterface_Update_Call) RunAndReturn(run func(*models.Auction) error) *AuctionRepositoryInterface_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewAuctionRepositoryInterface creates a new instance of AuctionRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuctionRepositoryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuctionRepositoryInterface {
	mock := &AuctionRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
