// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	auction "github.com/susek555/BD2/car-dealer-api/internal/domains/auction"

	models "github.com/susek555/BD2/car-dealer-api/internal/models"
)

// AuctionServiceInterface is an autogenerated mock type for the AuctionServiceInterface type
type AuctionServiceInterface struct {
	mock.Mock
}

type AuctionServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *AuctionServiceInterface) EXPECT() *AuctionServiceInterface_Expecter {
	return &AuctionServiceInterface_Expecter{mock: &_m.Mock}
}

// BuyNow provides a mock function with given fields: auctionID, userID
func (_m *AuctionServiceInterface) BuyNow(auctionID uint, userID uint) (*models.Auction, error) {
	ret := _m.Called(auctionID, userID)

	if len(ret) == 0 {
		panic("no return value specified for BuyNow")
	}

	var r0 *models.Auction
	var r1 error
	if rf, ok := ret.Get(0).(func(uint, uint) (*models.Auction, error)); ok {
		return rf(auctionID, userID)
	}
	if rf, ok := ret.Get(0).(func(uint, uint) *models.Auction); ok {
		r0 = rf(auctionID, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Auction)
		}
	}

	if rf, ok := ret.Get(1).(func(uint, uint) error); ok {
		r1 = rf(auctionID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AuctionServiceInterface_BuyNow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BuyNow'
type AuctionServiceInterface_BuyNow_Call struct {
	*mock.Call
}

// BuyNow is a helper method to define mock.On call
//   - auctionID uint
//   - userID uint
func (_e *AuctionServiceInterface_Expecter) BuyNow(auctionID interface{}, userID interface{}) *AuctionServiceInterface_BuyNow_Call {
	return &AuctionServiceInterface_BuyNow_Call{Call: _e.mock.On("BuyNow", auctionID, userID)}
}

func (_c *AuctionServiceInterface_BuyNow_Call) Run(run func(auctionID uint, userID uint)) *AuctionServiceInterface_BuyNow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint), args[1].(uint))
	})
	return _c
}

func (_c *AuctionServiceInterface_BuyNow_Call) Return(_a0 *models.Auction, _a1 error) *AuctionServiceInterface_BuyNow_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AuctionServiceInterface_BuyNow_Call) RunAndReturn(run func(uint, uint) (*models.Auction, error)) *AuctionServiceInterface_BuyNow_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: _a0
func (_m *AuctionServiceInterface) Create(_a0 *auction.CreateAuctionDTO) (*auction.RetrieveAuctionDTO, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *auction.RetrieveAuctionDTO
	var r1 error
	if rf, ok := ret.Get(0).(func(*auction.CreateAuctionDTO) (*auction.RetrieveAuctionDTO, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(*auction.CreateAuctionDTO) *auction.RetrieveAuctionDTO); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auction.RetrieveAuctionDTO)
		}
	}

	if rf, ok := ret.Get(1).(func(*auction.CreateAuctionDTO) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AuctionServiceInterface_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type AuctionServiceInterface_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - _a0 *auction.CreateAuctionDTO
func (_e *AuctionServiceInterface_Expecter) Create(_a0 interface{}) *AuctionServiceInterface_Create_Call {
	return &AuctionServiceInterface_Create_Call{Call: _e.mock.On("Create", _a0)}
}

func (_c *AuctionServiceInterface_Create_Call) Run(run func(_a0 *auction.CreateAuctionDTO)) *AuctionServiceInterface_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*auction.CreateAuctionDTO))
	})
	return _c
}

func (_c *AuctionServiceInterface_Create_Call) Return(_a0 *auction.RetrieveAuctionDTO, _a1 error) *AuctionServiceInterface_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AuctionServiceInterface_Create_Call) RunAndReturn(run func(*auction.CreateAuctionDTO) (*auction.RetrieveAuctionDTO, error)) *AuctionServiceInterface_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: id, userId
func (_m *AuctionServiceInterface) Delete(id uint, userId uint) error {
	ret := _m.Called(id, userId)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint, uint) error); ok {
		r0 = rf(id, userId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AuctionServiceInterface_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type AuctionServiceInterface_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - id uint
//   - userId uint
func (_e *AuctionServiceInterface_Expecter) Delete(id interface{}, userId interface{}) *AuctionServiceInterface_Delete_Call {
	return &AuctionServiceInterface_Delete_Call{Call: _e.mock.On("Delete", id, userId)}
}

func (_c *AuctionServiceInterface_Delete_Call) Run(run func(id uint, userId uint)) *AuctionServiceInterface_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint), args[1].(uint))
	})
	return _c
}

func (_c *AuctionServiceInterface_Delete_Call) Return(_a0 error) *AuctionServiceInterface_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AuctionServiceInterface_Delete_Call) RunAndReturn(run func(uint, uint) error) *AuctionServiceInterface_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function with no fields
func (_m *AuctionServiceInterface) GetAll() ([]auction.RetrieveAuctionDTO, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []auction.RetrieveAuctionDTO
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]auction.RetrieveAuctionDTO, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []auction.RetrieveAuctionDTO); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]auction.RetrieveAuctionDTO)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AuctionServiceInterface_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type AuctionServiceInterface_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
func (_e *AuctionServiceInterface_Expecter) GetAll() *AuctionServiceInterface_GetAll_Call {
	return &AuctionServiceInterface_GetAll_Call{Call: _e.mock.On("GetAll")}
}

func (_c *AuctionServiceInterface_GetAll_Call) Run(run func()) *AuctionServiceInterface_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *AuctionServiceInterface_GetAll_Call) Return(_a0 []auction.RetrieveAuctionDTO, _a1 error) *AuctionServiceInterface_GetAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AuctionServiceInterface_GetAll_Call) RunAndReturn(run func() ([]auction.RetrieveAuctionDTO, error)) *AuctionServiceInterface_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetById provides a mock function with given fields: id
func (_m *AuctionServiceInterface) GetById(id uint) (*auction.RetrieveAuctionDTO, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetById")
	}

	var r0 *auction.RetrieveAuctionDTO
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (*auction.RetrieveAuctionDTO, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uint) *auction.RetrieveAuctionDTO); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auction.RetrieveAuctionDTO)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AuctionServiceInterface_GetById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetById'
type AuctionServiceInterface_GetById_Call struct {
	*mock.Call
}

// GetById is a helper method to define mock.On call
//   - id uint
func (_e *AuctionServiceInterface_Expecter) GetById(id interface{}) *AuctionServiceInterface_GetById_Call {
	return &AuctionServiceInterface_GetById_Call{Call: _e.mock.On("GetById", id)}
}

func (_c *AuctionServiceInterface_GetById_Call) Run(run func(id uint)) *AuctionServiceInterface_GetById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint))
	})
	return _c
}

func (_c *AuctionServiceInterface_GetById_Call) Return(_a0 *auction.RetrieveAuctionDTO, _a1 error) *AuctionServiceInterface_GetById_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AuctionServiceInterface_GetById_Call) RunAndReturn(run func(uint) (*auction.RetrieveAuctionDTO, error)) *AuctionServiceInterface_GetById_Call {
	_c.Call.Return(run)
	return _c
}

// GetByIdNonDTO provides a mock function with given fields: id
func (_m *AuctionServiceInterface) GetByIdNonDTO(id uint) (*models.Auction, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByIdNonDTO")
	}

	var r0 *models.Auction
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (*models.Auction, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uint) *models.Auction); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Auction)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AuctionServiceInterface_GetByIdNonDTO_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByIdNonDTO'
type AuctionServiceInterface_GetByIdNonDTO_Call struct {
	*mock.Call
}

// GetByIdNonDTO is a helper method to define mock.On call
//   - id uint
func (_e *AuctionServiceInterface_Expecter) GetByIdNonDTO(id interface{}) *AuctionServiceInterface_GetByIdNonDTO_Call {
	return &AuctionServiceInterface_GetByIdNonDTO_Call{Call: _e.mock.On("GetByIdNonDTO", id)}
}

func (_c *AuctionServiceInterface_GetByIdNonDTO_Call) Run(run func(id uint)) *AuctionServiceInterface_GetByIdNonDTO_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint))
	})
	return _c
}

func (_c *AuctionServiceInterface_GetByIdNonDTO_Call) Return(_a0 *models.Auction, _a1 error) *AuctionServiceInterface_GetByIdNonDTO_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AuctionServiceInterface_GetByIdNonDTO_Call) RunAndReturn(run func(uint) (*models.Auction, error)) *AuctionServiceInterface_GetByIdNonDTO_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: _a0, userID
func (_m *AuctionServiceInterface) Update(_a0 *auction.UpdateAuctionDTO, userID uint) (*auction.RetrieveAuctionDTO, error) {
	ret := _m.Called(_a0, userID)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *auction.RetrieveAuctionDTO
	var r1 error
	if rf, ok := ret.Get(0).(func(*auction.UpdateAuctionDTO, uint) (*auction.RetrieveAuctionDTO, error)); ok {
		return rf(_a0, userID)
	}
	if rf, ok := ret.Get(0).(func(*auction.UpdateAuctionDTO, uint) *auction.RetrieveAuctionDTO); ok {
		r0 = rf(_a0, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auction.RetrieveAuctionDTO)
		}
	}

	if rf, ok := ret.Get(1).(func(*auction.UpdateAuctionDTO, uint) error); ok {
		r1 = rf(_a0, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AuctionServiceInterface_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type AuctionServiceInterface_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - _a0 *auction.UpdateAuctionDTO
//   - userID uint
func (_e *AuctionServiceInterface_Expecter) Update(_a0 interface{}, userID interface{}) *AuctionServiceInterface_Update_Call {
	return &AuctionServiceInterface_Update_Call{Call: _e.mock.On("Update", _a0, userID)}
}

func (_c *AuctionServiceInterface_Update_Call) Run(run func(_a0 *auction.UpdateAuctionDTO, userID uint)) *AuctionServiceInterface_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*auction.UpdateAuctionDTO), args[1].(uint))
	})
	return _c
}

func (_c *AuctionServiceInterface_Update_Call) Return(_a0 *auction.RetrieveAuctionDTO, _a1 error) *AuctionServiceInterface_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AuctionServiceInterface_Update_Call) RunAndReturn(run func(*auction.UpdateAuctionDTO, uint) (*auction.RetrieveAuctionDTO, error)) *AuctionServiceInterface_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewAuctionServiceInterface creates a new instance of AuctionServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuctionServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuctionServiceInterface {
	mock := &AuctionServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
