// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	bid "github.com/susek555/BD2/car-dealer-api/internal/domains/models"
)

// BidRepositoryInterface is an autogenerated mock type for the BidRepositoryInterface type
type BidRepositoryInterface struct {
	mock.Mock
}

type BidRepositoryInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *BidRepositoryInterface) EXPECT() *BidRepositoryInterface_Expecter {
	return &BidRepositoryInterface_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: _a0
func (_m *BidRepositoryInterface) Create(_a0 *bid.Bid) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*bid.Bid) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// BidRepositoryInterface_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type BidRepositoryInterface_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - _a0 *bid.Bid
func (_e *BidRepositoryInterface_Expecter) Create(_a0 interface{}) *BidRepositoryInterface_Create_Call {
	return &BidRepositoryInterface_Create_Call{Call: _e.mock.On("Create", _a0)}
}

func (_c *BidRepositoryInterface_Create_Call) Run(run func(_a0 *bid.Bid)) *BidRepositoryInterface_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*bid.Bid))
	})
	return _c
}

func (_c *BidRepositoryInterface_Create_Call) Return(_a0 error) *BidRepositoryInterface_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *BidRepositoryInterface_Create_Call) RunAndReturn(run func(*bid.Bid) error) *BidRepositoryInterface_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function with no fields
func (_m *BidRepositoryInterface) GetAll() ([]bid.Bid, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []bid.Bid
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]bid.Bid, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []bid.Bid); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]bid.Bid)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BidRepositoryInterface_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type BidRepositoryInterface_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
func (_e *BidRepositoryInterface_Expecter) GetAll() *BidRepositoryInterface_GetAll_Call {
	return &BidRepositoryInterface_GetAll_Call{Call: _e.mock.On("GetAll")}
}

func (_c *BidRepositoryInterface_GetAll_Call) Run(run func()) *BidRepositoryInterface_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *BidRepositoryInterface_GetAll_Call) Return(_a0 []bid.Bid, _a1 error) *BidRepositoryInterface_GetAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *BidRepositoryInterface_GetAll_Call) RunAndReturn(run func() ([]bid.Bid, error)) *BidRepositoryInterface_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetByAuctionId provides a mock function with given fields: auctionID
func (_m *BidRepositoryInterface) GetByAuctionId(auctionID uint) ([]bid.Bid, error) {
	ret := _m.Called(auctionID)

	if len(ret) == 0 {
		panic("no return value specified for GetByAuctionId")
	}

	var r0 []bid.Bid
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) ([]bid.Bid, error)); ok {
		return rf(auctionID)
	}
	if rf, ok := ret.Get(0).(func(uint) []bid.Bid); ok {
		r0 = rf(auctionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]bid.Bid)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(auctionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BidRepositoryInterface_GetByAuctionId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByAuctionId'
type BidRepositoryInterface_GetByAuctionId_Call struct {
	*mock.Call
}

// GetByAuctionId is a helper method to define mock.On call
//   - auctionID uint
func (_e *BidRepositoryInterface_Expecter) GetByAuctionId(auctionID interface{}) *BidRepositoryInterface_GetByAuctionId_Call {
	return &BidRepositoryInterface_GetByAuctionId_Call{Call: _e.mock.On("GetByAuctionId", auctionID)}
}

func (_c *BidRepositoryInterface_GetByAuctionId_Call) Run(run func(auctionID uint)) *BidRepositoryInterface_GetByAuctionId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint))
	})
	return _c
}

func (_c *BidRepositoryInterface_GetByAuctionId_Call) Return(_a0 []bid.Bid, _a1 error) *BidRepositoryInterface_GetByAuctionId_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *BidRepositoryInterface_GetByAuctionId_Call) RunAndReturn(run func(uint) ([]bid.Bid, error)) *BidRepositoryInterface_GetByAuctionId_Call {
	_c.Call.Return(run)
	return _c
}

// GetByBidderId provides a mock function with given fields: bidderID
func (_m *BidRepositoryInterface) GetByBidderId(bidderID uint) ([]bid.Bid, error) {
	ret := _m.Called(bidderID)

	if len(ret) == 0 {
		panic("no return value specified for GetByBidderId")
	}

	var r0 []bid.Bid
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) ([]bid.Bid, error)); ok {
		return rf(bidderID)
	}
	if rf, ok := ret.Get(0).(func(uint) []bid.Bid); ok {
		r0 = rf(bidderID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]bid.Bid)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(bidderID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BidRepositoryInterface_GetByBidderId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByBidderId'
type BidRepositoryInterface_GetByBidderId_Call struct {
	*mock.Call
}

// GetByBidderId is a helper method to define mock.On call
//   - bidderID uint
func (_e *BidRepositoryInterface_Expecter) GetByBidderId(bidderID interface{}) *BidRepositoryInterface_GetByBidderId_Call {
	return &BidRepositoryInterface_GetByBidderId_Call{Call: _e.mock.On("GetByBidderId", bidderID)}
}

func (_c *BidRepositoryInterface_GetByBidderId_Call) Run(run func(bidderID uint)) *BidRepositoryInterface_GetByBidderId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint))
	})
	return _c
}

func (_c *BidRepositoryInterface_GetByBidderId_Call) Return(_a0 []bid.Bid, _a1 error) *BidRepositoryInterface_GetByBidderId_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *BidRepositoryInterface_GetByBidderId_Call) RunAndReturn(run func(uint) ([]bid.Bid, error)) *BidRepositoryInterface_GetByBidderId_Call {
	_c.Call.Return(run)
	return _c
}

// GetById provides a mock function with given fields: id
func (_m *BidRepositoryInterface) GetById(id uint) (*bid.Bid, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetById")
	}

	var r0 *bid.Bid
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (*bid.Bid, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uint) *bid.Bid); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bid.Bid)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BidRepositoryInterface_GetById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetById'
type BidRepositoryInterface_GetById_Call struct {
	*mock.Call
}

// GetById is a helper method to define mock.On call
//   - id uint
func (_e *BidRepositoryInterface_Expecter) GetById(id interface{}) *BidRepositoryInterface_GetById_Call {
	return &BidRepositoryInterface_GetById_Call{Call: _e.mock.On("GetById", id)}
}

func (_c *BidRepositoryInterface_GetById_Call) Run(run func(id uint)) *BidRepositoryInterface_GetById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint))
	})
	return _c
}

func (_c *BidRepositoryInterface_GetById_Call) Return(_a0 *bid.Bid, _a1 error) *BidRepositoryInterface_GetById_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *BidRepositoryInterface_GetById_Call) RunAndReturn(run func(uint) (*bid.Bid, error)) *BidRepositoryInterface_GetById_Call {
	_c.Call.Return(run)
	return _c
}

// GetHighestBid provides a mock function with given fields: auctionID
func (_m *BidRepositoryInterface) GetHighestBid(auctionID uint) (*bid.Bid, error) {
	ret := _m.Called(auctionID)

	if len(ret) == 0 {
		panic("no return value specified for GetHighestBid")
	}

	var r0 *bid.Bid
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (*bid.Bid, error)); ok {
		return rf(auctionID)
	}
	if rf, ok := ret.Get(0).(func(uint) *bid.Bid); ok {
		r0 = rf(auctionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bid.Bid)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(auctionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BidRepositoryInterface_GetHighestBid_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHighestBid'
type BidRepositoryInterface_GetHighestBid_Call struct {
	*mock.Call
}

// GetHighestBid is a helper method to define mock.On call
//   - auctionID uint
func (_e *BidRepositoryInterface_Expecter) GetHighestBid(auctionID interface{}) *BidRepositoryInterface_GetHighestBid_Call {
	return &BidRepositoryInterface_GetHighestBid_Call{Call: _e.mock.On("GetHighestBid", auctionID)}
}

func (_c *BidRepositoryInterface_GetHighestBid_Call) Run(run func(auctionID uint)) *BidRepositoryInterface_GetHighestBid_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint))
	})
	return _c
}

func (_c *BidRepositoryInterface_GetHighestBid_Call) Return(_a0 *bid.Bid, _a1 error) *BidRepositoryInterface_GetHighestBid_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *BidRepositoryInterface_GetHighestBid_Call) RunAndReturn(run func(uint) (*bid.Bid, error)) *BidRepositoryInterface_GetHighestBid_Call {
	_c.Call.Return(run)
	return _c
}

// GetHighestBidByUserId provides a mock function with given fields: auctionID, userID
func (_m *BidRepositoryInterface) GetHighestBidByUserId(auctionID uint, userID uint) (*bid.Bid, error) {
	ret := _m.Called(auctionID, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetHighestBidByUserId")
	}

	var r0 *bid.Bid
	var r1 error
	if rf, ok := ret.Get(0).(func(uint, uint) (*bid.Bid, error)); ok {
		return rf(auctionID, userID)
	}
	if rf, ok := ret.Get(0).(func(uint, uint) *bid.Bid); ok {
		r0 = rf(auctionID, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bid.Bid)
		}
	}

	if rf, ok := ret.Get(1).(func(uint, uint) error); ok {
		r1 = rf(auctionID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BidRepositoryInterface_GetHighestBidByUserId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHighestBidByUserId'
type BidRepositoryInterface_GetHighestBidByUserId_Call struct {
	*mock.Call
}

// GetHighestBidByUserId is a helper method to define mock.On call
//   - auctionID uint
//   - userID uint
func (_e *BidRepositoryInterface_Expecter) GetHighestBidByUserId(auctionID interface{}, userID interface{}) *BidRepositoryInterface_GetHighestBidByUserId_Call {
	return &BidRepositoryInterface_GetHighestBidByUserId_Call{Call: _e.mock.On("GetHighestBidByUserId", auctionID, userID)}
}

func (_c *BidRepositoryInterface_GetHighestBidByUserId_Call) Run(run func(auctionID uint, userID uint)) *BidRepositoryInterface_GetHighestBidByUserId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint), args[1].(uint))
	})
	return _c
}

func (_c *BidRepositoryInterface_GetHighestBidByUserId_Call) Return(_a0 *bid.Bid, _a1 error) *BidRepositoryInterface_GetHighestBidByUserId_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *BidRepositoryInterface_GetHighestBidByUserId_Call) RunAndReturn(run func(uint, uint) (*bid.Bid, error)) *BidRepositoryInterface_GetHighestBidByUserId_Call {
	_c.Call.Return(run)
	return _c
}

// NewBidRepositoryInterface creates a new instance of BidRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBidRepositoryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *BidRepositoryInterface {
	mock := &BidRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
