// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	models "github.com/susek555/BD2/car-dealer-api/internal/models"
)

// SaleOfferRetrieverInterface is an autogenerated mock type for the SaleOfferRetrieverInterface type
type SaleOfferRetrieverInterface struct {
	mock.Mock
}

type SaleOfferRetrieverInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *SaleOfferRetrieverInterface) EXPECT() *SaleOfferRetrieverInterface_Expecter {
	return &SaleOfferRetrieverInterface_Expecter{mock: &_m.Mock}
}

// GetByID provides a mock function with given fields: id
func (_m *SaleOfferRetrieverInterface) GetByID(id uint) (*models.SaleOffer, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.SaleOffer
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (*models.SaleOffer, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uint) *models.SaleOffer); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.SaleOffer)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SaleOfferRetrieverInterface_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type SaleOfferRetrieverInterface_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - id uint
func (_e *SaleOfferRetrieverInterface_Expecter) GetByID(id interface{}) *SaleOfferRetrieverInterface_GetByID_Call {
	return &SaleOfferRetrieverInterface_GetByID_Call{Call: _e.mock.On("GetByID", id)}
}

func (_c *SaleOfferRetrieverInterface_GetByID_Call) Run(run func(id uint)) *SaleOfferRetrieverInterface_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint))
	})
	return _c
}

func (_c *SaleOfferRetrieverInterface_GetByID_Call) Return(_a0 *models.SaleOffer, _a1 error) *SaleOfferRetrieverInterface_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *SaleOfferRetrieverInterface_GetByID_Call) RunAndReturn(run func(uint) (*models.SaleOffer, error)) *SaleOfferRetrieverInterface_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// NewSaleOfferRetrieverInterface creates a new instance of SaleOfferRetrieverInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSaleOfferRetrieverInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *SaleOfferRetrieverInterface {
	mock := &SaleOfferRetrieverInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
