// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	notification "github.com/susek555/BD2/car-dealer-api/internal/domains/notification"
)

// SaleOfferRetrieverInterface is an autogenerated mock type for the SaleOfferRetrieverInterface type
type SaleOfferRetrieverInterface struct {
	mock.Mock
}

type SaleOfferRetrieverInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *SaleOfferRetrieverInterface) EXPECT() *SaleOfferRetrieverInterface_Expecter {
	return &SaleOfferRetrieverInterface_Expecter{mock: &_m.Mock}
}

// GetDetailedByID provides a mock function with given fields: id, userID
func (_m *SaleOfferRetrieverInterface) GetDetailedByID(id uint, userID *uint) (notification.SaleOfferInterface, error) {
	ret := _m.Called(id, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetDetailedByID")
	}

	var r0 notification.SaleOfferInterface
	var r1 error
	if rf, ok := ret.Get(0).(func(uint, *uint) (notification.SaleOfferInterface, error)); ok {
		return rf(id, userID)
	}
	if rf, ok := ret.Get(0).(func(uint, *uint) notification.SaleOfferInterface); ok {
		r0 = rf(id, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(notification.SaleOfferInterface)
		}
	}

	if rf, ok := ret.Get(1).(func(uint, *uint) error); ok {
		r1 = rf(id, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SaleOfferRetrieverInterface_GetDetailedByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDetailedByID'
type SaleOfferRetrieverInterface_GetDetailedByID_Call struct {
	*mock.Call
}

// GetDetailedByID is a helper method to define mock.On call
//   - id uint
//   - userID *uint
func (_e *SaleOfferRetrieverInterface_Expecter) GetDetailedByID(id interface{}, userID interface{}) *SaleOfferRetrieverInterface_GetDetailedByID_Call {
	return &SaleOfferRetrieverInterface_GetDetailedByID_Call{Call: _e.mock.On("GetDetailedByID", id, userID)}
}

func (_c *SaleOfferRetrieverInterface_GetDetailedByID_Call) Run(run func(id uint, userID *uint)) *SaleOfferRetrieverInterface_GetDetailedByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint), args[1].(*uint))
	})
	return _c
}

func (_c *SaleOfferRetrieverInterface_GetDetailedByID_Call) Return(_a0 notification.SaleOfferInterface, _a1 error) *SaleOfferRetrieverInterface_GetDetailedByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *SaleOfferRetrieverInterface_GetDetailedByID_Call) RunAndReturn(run func(uint, *uint) (notification.SaleOfferInterface, error)) *SaleOfferRetrieverInterface_GetDetailedByID_Call {
	_c.Call.Return(run)
	return _c
}

// NewSaleOfferRetrieverInterface creates a new instance of SaleOfferRetrieverInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSaleOfferRetrieverInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *SaleOfferRetrieverInterface {
	mock := &SaleOfferRetrieverInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
