definitions:
  auth.LoginInput:
    properties:
      login:
        type: string
      password:
        type: string
    required:
    - login
    - password
    type: object
  auth.LoginResponse:
    properties:
      access_token:
        type: string
      company_name:
        type: string
      company_nip:
        type: string
      email:
        type: string
      errors:
        additionalProperties:
          items:
            type: string
          type: array
        type: object
      person_name:
        type: string
      person_surname:
        type: string
      refresh_token:
        type: string
      selector:
        type: string
      username:
        type: string
    type: object
  auth.LogoutInput:
    properties:
      all_devices:
        type: boolean
      refresh_token:
        type: string
    type: object
  auth.RefreshInput:
    properties:
      refresh_token:
        type: string
    required:
    - refresh_token
    type: object
  auth.RegisterResponse:
    properties:
      errors:
        additionalProperties:
          items:
            type: string
          type: array
        type: object
    type: object
  custom_errors.HTTPError:
    properties:
      error_description:
        type: string
    type: object
  review.Review:
    properties:
      description:
        type: string
      id:
        type: integer
      rating:
        type: integer
      reviewee:
        $ref: '#/definitions/user.User'
      reviewee_id:
        type: integer
      reviewer:
        $ref: '#/definitions/user.User'
      reviewer_id:
        type: integer
    type: object
  review.ReviewDTO:
    properties:
      description:
        type: string
      id:
        type: integer
      rating:
        type: integer
      reviewee:
        $ref: '#/definitions/review.UserDTO'
      reviewer:
        $ref: '#/definitions/review.UserDTO'
    type: object
  review.UserDTO:
    properties:
      id:
        type: integer
      username:
        type: string
    type: object
  user.Company:
    properties:
      id:
        type: integer
      name:
        type: string
      nip:
        type: string
      user:
        $ref: '#/definitions/user.User'
    type: object
  user.CreateUserDTO:
    properties:
      company_name:
        type: string
      company_nip:
        type: string
      email:
        type: string
      password:
        type: string
      person_name:
        type: string
      person_surname:
        type: string
      selector:
        type: string
      username:
        type: string
    required:
    - email
    type: object
  user.Person:
    properties:
      id:
        type: integer
      name:
        type: string
      surname:
        type: string
      user:
        $ref: '#/definitions/user.User'
    type: object
  user.RetrieveUserDTO:
    properties:
      company_name:
        type: string
      company_nip:
        type: string
      email:
        type: string
      person_name:
        type: string
      person_surname:
        type: string
      username:
        type: string
    type: object
  user.UpdateUserDTO:
    properties:
      email:
        type: string
      id:
        type: integer
      password:
        type: string
      username:
        type: string
    type: object
  user.User:
    properties:
      company:
        $ref: '#/definitions/user.Company'
      email:
        type: string
      id:
        type: integer
      password:
        type: string
      person:
        $ref: '#/definitions/user.Person'
      selector:
        type: string
      username:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    name: BD2
  description: Car-Dealer API
  license:
    name: MIT
  title: Car‑Dealer API
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: Authenticate user and return a pair of tokens and user data
      parameters:
      - description: Login form
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/auth.LoginInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK - returns tokens and data of the user
          schema:
            $ref: '#/definitions/auth.LoginResponse'
        "400":
          description: Invalid input data
          schema:
            $ref: '#/definitions/auth.LoginResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/auth.LoginResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/auth.LoginResponse'
      summary: Login user
      tags:
      - auth
  /auth/refresh:
    post:
      consumes:
      - application/json
      description: Refresh access tokens
      parameters:
      - description: Refresh token form
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/auth.RefreshInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK - returns new access token
          schema:
            $ref: '#/definitions/auth.LoginResponse'
        "400":
          description: Invalid input data
          schema:
            $ref: '#/definitions/custom_errors.HTTPError'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/custom_errors.HTTPError'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/custom_errors.HTTPError'
      summary: Refresh tokens
      tags:
      - auth
  /auth/register:
    post:
      consumes:
      - application/json
      description: Set up account and return the status
      parameters:
      - description: Registration form
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/user.CreateUserDTO'
      produces:
      - application/json
      responses:
        "201":
          description: Created - returns tokens
          schema:
            $ref: '#/definitions/auth.RegisterResponse'
        "400":
          description: Invalid input data
          schema:
            $ref: '#/definitions/auth.RegisterResponse'
        "409":
          description: Login taken
          schema:
            $ref: '#/definitions/auth.RegisterResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/auth.RegisterResponse'
      summary: Register new user
      tags:
      - auth
  /logout:
    post:
      consumes:
      - application/json
      description: Logout user and invalidate refresh token
      parameters:
      - description: Logout form
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/auth.LogoutInput'
      produces:
      - application/json
      responses:
        "204":
          description: No content
          schema:
            $ref: '#/definitions/custom_errors.HTTPError'
        "400":
          description: Invalid input data
          schema:
            $ref: '#/definitions/custom_errors.HTTPError'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/custom_errors.HTTPError'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/custom_errors.HTTPError'
      summary: Logout user
      tags:
      - auth
  /review:
    get:
      description: Returns every review in the system as an array of DTOs.
      operationId: getAllReviews
      produces:
      - application/json
      responses:
        "200":
          description: OK – list of reviews
          schema:
            items:
              $ref: '#/definitions/review.ReviewDTO'
            type: array
        "400":
          description: Bad Request – query failed
          schema:
            $ref: '#/definitions/custom_errors.HTTPError'
      summary: List all reviews
      tags:
      - reviews
    post:
      consumes:
      - application/json
      description: Persists a new review entity and returns the created review.
      operationId: createReview
      parameters:
      - description: Review payload
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/review.Review'
      produces:
      - application/json
      responses:
        "201":
          description: Created – review stored
          schema:
            $ref: '#/definitions/review.ReviewDTO'
        "400":
          description: Bad Request – validation or persistence error
          schema:
            $ref: '#/definitions/custom_errors.HTTPError'
      summary: Create a new review
      tags:
      - reviews
    put:
      consumes:
      - application/json
      description: Updates a review and returns the updated entity.
      operationId: updateReview
      parameters:
      - description: Review payload
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/review.Review'
      produces:
      - application/json
      responses:
        "200":
          description: OK – review updated
          schema:
            $ref: '#/definitions/review.ReviewDTO'
        "400":
          description: Bad Request – validation or update error
          schema:
            $ref: '#/definitions/custom_errors.HTTPError'
      summary: Update an existing review
      tags:
      - reviews
  /review/{id}:
    delete:
      description: Deletes the review identified by its ID.
      operationId: deleteReview
      parameters:
      - description: Review ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "204":
          description: No Content – review deleted
          schema:
            type: string
        "400":
          description: Bad Request – invalid ID format or delete failed
          schema:
            $ref: '#/definitions/custom_errors.HTTPError'
      summary: Delete a review
      tags:
      - reviews
    get:
      description: Returns review that match given id as an DTO.
      operationId: getReviewById
      parameters:
      - description: Review id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK – review with given id
          schema:
            $ref: '#/definitions/review.ReviewDTO'
        "400":
          description: Bad Request – query failed
          schema:
            $ref: '#/definitions/custom_errors.HTTPError'
      summary: Get review by id
      tags:
      - reviews
  /review/reviewee/{id}:
    get:
      description: Returns all reviews where the given user is the reviewee.
      operationId: getReviewsByRevieweeId
      parameters:
      - description: Reviewee ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK – list of reviews
          schema:
            items:
              $ref: '#/definitions/review.ReviewDTO'
            type: array
        "400":
          description: Bad Request – invalid ID format or query failed
          schema:
            $ref: '#/definitions/custom_errors.HTTPError'
      summary: List reviews about a reviewee
      tags:
      - reviews
  /review/reviewer/{id}:
    get:
      description: Returns all reviews authored by the reviewer specified by ID.
      operationId: getReviewsByReviewerId
      parameters:
      - description: Reviewer ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK – list of reviews
          schema:
            items:
              $ref: '#/definitions/review.ReviewDTO'
            type: array
        "400":
          description: Bad Request – invalid ID format or query failed
          schema:
            $ref: '#/definitions/custom_errors.HTTPError'
      summary: List reviews written by a reviewer
      tags:
      - reviews
  /review/reviewer/{reviewerId}/reviewee/{revieweeId}:
    get:
      description: Returns the review where <reviewerId> is the author and <revieweeId>
        is the subject.
      operationId: getReviewByReviewerAndReviewee
      parameters:
      - description: Reviewer ID
        in: path
        name: reviewerId
        required: true
        type: integer
      - description: Reviewee ID
        in: path
        name: revieweeId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK – review found
          schema:
            $ref: '#/definitions/review.ReviewDTO'
        "400":
          description: Bad Request – invalid ID format or query failed
          schema:
            $ref: '#/definitions/custom_errors.HTTPError'
      summary: Get review written by one user about another
      tags:
      - reviews
  /users:
    get:
      consumes:
      - application/json
      description: Get all users from database and return them as a list of DTOs.
        If user's subtype is person the company related fields will be omitted and
        vice versa.
      produces:
      - application/json
      responses:
        "200":
          description: List of users
          schema:
            items:
              $ref: '#/definitions/user.RetrieveUserDTO'
            type: array
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/custom_errors.HTTPError'
      summary: Get all users
      tags:
      - users
    put:
      consumes:
      - application/json
      description: Update user in database from DTO. Currently you can only change
        basic fields (email, username, password), not the subtype.
      parameters:
      - description: Update form
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/user.UpdateUserDTO'
      produces:
      - application/json
      responses:
        "200":
          description: User updated
          schema:
            $ref: '#/definitions/user.UpdateUserDTO'
        "400":
          description: Invalid input data
          schema:
            $ref: '#/definitions/custom_errors.HTTPError'
        "404":
          description: User not found
          schema:
            $ref: '#/definitions/custom_errors.HTTPError'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/custom_errors.HTTPError'
      summary: Update user
      tags:
      - users
  /users/{id}:
    delete:
      consumes:
      - application/json
      description: Delete user from database by id.
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: User sucessfully deleted
        "400":
          description: Id is not a number
          schema:
            $ref: '#/definitions/custom_errors.HTTPError'
        "404":
          description: User not found
          schema:
            $ref: '#/definitions/custom_errors.HTTPError'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/custom_errors.HTTPError'
      summary: Delete user
      tags:
      - users
  /users/email/{email}:
    get:
      consumes:
      - application/json
      description: Get user by email from database and return it as a DTO. If user's
        subtype is person the company related fields will be omitted and vice versa.
      parameters:
      - description: User email
        in: path
        name: email
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: User found
          schema:
            $ref: '#/definitions/user.RetrieveUserDTO'
        "404":
          description: User not found
          schema:
            $ref: '#/definitions/custom_errors.HTTPError'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/custom_errors.HTTPError'
      summary: Get user by email
      tags:
      - users
  /users/id/{id}:
    get:
      consumes:
      - application/json
      description: Get user by id from database and return it as a DTO. If user's
        subtype is person the company related fields will be omitted and vice versa.
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: User
          schema:
            $ref: '#/definitions/user.RetrieveUserDTO'
        "400":
          description: Id is not a number
          schema:
            $ref: '#/definitions/custom_errors.HTTPError'
        "404":
          description: User not found
          schema:
            $ref: '#/definitions/custom_errors.HTTPError'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/custom_errors.HTTPError'
      summary: Get user by id
      tags:
      - users
schemes:
- http
swagger: "2.0"
